### ISSUE TITLE
having the `pkgdown` website URL on the repo page

### ISSUE THREAD

**Issue by IndrajeetPatil** [BlasBenito/spatialRF#3]
I see that there is an associated `pkgdown` website for the R package, but it's a bit difficult to find. 

Usually, one would expect to find it here on the repo page:

<img width="310" alt="Screenshot 2021-05-04 at 23 39 18" src="https://user-images.githubusercontent.com/11330453/117073368-18254d80-ad32-11eb-878b-d40ef5521b65.png">

Hope this is of interest.

**Comment by BlasBenito** [comment]
Dear Indrajeet,
it is definitely of interest, I totally missed that, but it is fixed now.
Thank you very much!

**Comment by IndrajeetPatil** [comment]
Perfect! :)
