### ISSUE TITLE
prediction for the test data

### ISSUE THREAD

**Issue by zhlhkbu** [BlasBenito/spatialRF#7]

**Comment by K-Ibadullaev** [comment]
Dear @BlasBenito, thank you for the great package!
Perhaps, I have similar question as it was above. 
What is the right way to supply xy's and distance matrix of test data to the trained spatial RF for prediction?
I suppose, it doesn't take the colum names from training data and looks for same columns in the test data, right?
Thank you in advance!


`#fitting, tuning, evaluating, and repeating a model
model.full <- rf_spatial(
  data = upper_gsi_sub,
  dependent.variable.name = UP_dependent.variable.name,
  predictor.variable.names = UP_predictor.variable.names,
  distance.matrix = as.matrix(UP_distance),
  distance.thresholds = distance.thresholds,
  xy = UP_xy, #not needed by rf, but other functions read it from the model
  seed = random.seed,
  cluster = local.cluster #is passed via pipe to the other functions
) %>%
  rf_tuning() %>%
  rf_evaluate() %>%
  rf_repeat()

**#Store predictions 
# How to override xy and distance matrix???**
predicted <- stats::predict(
  object = model.full,
  data = upper_gsi_sub[!sample],
  type = "response"
    
)$predictions
#stopping the cluster
parallel::stopCluster(cl = local.cluster)`
